import { Product, Sizes } from "./types";
export const shirtNames = [
  "ANTI CECIL",
  "ARCADE",
  "ARIN HALLOWEEN",
  "BEAT EM UP",
  "STARCHEER (Purple)",
  "CARBUNCLE",
  "CLASSIC GRUMP",
  "GHAC TEE (GREEN)",
  "GREY 10MPH",
  "GHOUL GRUMPS",
  "ESSENTIAL TEE",
  "JINGLE GRUMP",
  "JSE HDWGH",
  "KENTO TEE",
  "KENTO TANK",
  "MANGA 1",
  "MANGA 2",
  "MANGA 3",
  "MR BIZ",
  "NAVY GRUMPS",
  "NSP 2018",
  "DINO PJ PANTS",
  "PAJAMA TOPS",
  "PRO CECIL",
  "SB MOON TEE",
  "SB NEW LOGO",
  "SB OLD LOGO",
  "SAKURA",
  "SCHOOL (PINK)",
  "SHUFFLEMASTER",
  "SJG BLK",
  "SJG GLITCH",
  "STARCHEER",
  "TENNIS (GREY)",
  "TENNIS (WHITE)",
  "TENNIS (TANK)",
  "TENNIS JOGGER",
  "DREAM D TANK",
  "DREAM D CROP",
  "ARCADE (WHITE)",
  "VGB",
  "WINDBREAKER",
  "YASHO",
  "ZELDA",
  "HALLOWEEN PJ ",
  "2012 TEE",
  "POP STAR TEE",
];
export const accessoryNames = [
  "Are We Insured",
  "Arin Hat",
  "Arin Plush Head",
  "Bandaids",
  "Bandana",
  "Beanies",
  "Blankets",
  "Bottle Opener",
  "Bottles (BLUE)",
  "Bottles (ORANGE)",
  "Bunny Grumps",
  "Cheeseman",
  "Classic Sticker",
  "Classic Sticker 2",
  "Classic Spinning Keychain",
  "Dan Hat",
  "Dan Plush Head",
  "Dino Clips",
  "Dream Daddy Pin",
  "Facemasks",
  "The Guys Hat",
  "Ghoul Magnets",
  "GHAC Hardcover Books",
  "GHAC Paperback Books",
  "GHAC Pins",
  "Hedgehog Pins",
  "Lanyard - Burgie",
  "Lanyard - Fired + Missed",
  "Lanyard - Grump Heads",
  "Lanyard - Black + Orange",
  "Lanyard - The Guys",
  "Magnet Poetry",
  "MUG (YELLOW)",
  "MUG (BLUE)",
  "Mystery Pin",
  "Notebook",
  "Orange Pom Beanie",
  "Pocket Pin - Blue",
  "Pocket Pin - Green",
  "Pocket Pin - Orange",
  "Pocket Pin - Pink (Good)",
  "Pocket Pin - Pink (Bad)",
  "Puzzle",
  "RPG Stickers",
  "RPG W1",
  "RPG W2",
  "Scrunchie - Blue",
  "Scrunchie - Pink",
  "STICKY NOTES",
  "Socks",
  "Towel",
  "Valentines Pins",
  "Villager Sticker",
  "Villager Tote",
  "Wall Scroll OVA",
  "Wall Scroll Explosion",
  "Washi Tape Grumphead",
  "Washie Tape Burgie",
  "Washie Tape Fired + Missed",
  "XMAS Mugs",
];
export const specialAccessoryNames = [
  "BODY PILLOW - ARIN",
  "BODY PILLOW ARINA",
  "BODY PILLOW - FURRY ARIN",
  "BODY PILLOW - DAN",
  "BODY PILLOW DANIELLA",
  "BODY PILLOW - FURRY DAN",
];

export function generateMockProducts(): Product[] {
  const products: Product[] = [];
  for (let i = 0; i < shirtNames.length; i++) {
    products.push({
      description: shirtNames[i],
      size: Sizes[i % Sizes.length],
      category: "Shirt",
      price: Math.random() > 0.5 ? 24 : 34,
      quantity: Math.floor(Math.random() * 200),
      isSpecial: false,
    });
  }
  for (let i = 0; i < accessoryNames.length; i++) {
    products.push({
      description: accessoryNames[i],
      size: "N/A",
      category: "Accessory",
      price: Math.random() * 50 + 5,
      quantity: Math.floor(Math.random() * 200),
      isSpecial: false,
    });
  }
  for (let i = 0; i < specialAccessoryNames.length; i++) {
    products.push({
      description: specialAccessoryNames[i],
      size: "N/A",
      category: "Special Accessory",
      price: Math.random() * 20 + 90,
      quantity: Math.floor(Math.random() * 200),
      isSpecial: true,
    });
  }
  return products;
}
